#ifndef SECRETS_H
#define SECRETS_H

#define WIFI_SSID "NOME_REDE"
#define WIFI_PASSWORD "SENHA_REDE"
#define PORTA_MQTT 1883
#define BROKER_MQTT "ENDERECO_BROKER"
#define TOKEN_BROKER "TOKEN_BROKER"
#define TOPICO_MQTT "TOPICO"

#endif